# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\EpubBuilder\ui_mainwindow.ui'
#
# Created: Mon Feb 22 23:49:35 2016
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 421)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Builder.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_edit_text = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_edit_text.setEnabled(False)
        self.pushButton_edit_text.setObjectName("pushButton_edit_text")
        self.horizontalLayout.addWidget(self.pushButton_edit_text)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.pushButton_start_build = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start_build.setEnabled(False)
        self.pushButton_start_build.setObjectName("pushButton_start_build")
        self.horizontalLayout.addWidget(self.pushButton_start_build)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_bookpage = QtWidgets.QLabel(self.centralwidget)
        self.label_bookpage.setObjectName("label_bookpage")
        self.horizontalLayout_3.addWidget(self.label_bookpage)
        self.lineEdit_bookpage = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_bookpage.setObjectName("lineEdit_bookpage")
        self.horizontalLayout_3.addWidget(self.lineEdit_bookpage)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButton_qidian = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_qidian.setChecked(True)
        self.radioButton_qidian.setObjectName("radioButton_qidian")
        self.horizontalLayout_8.addWidget(self.radioButton_qidian)
        self.radioButton_chuangshi = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_chuangshi.setObjectName("radioButton_chuangshi")
        self.horizontalLayout_8.addWidget(self.radioButton_chuangshi)
        self.radioButton_zongheng = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_zongheng.setObjectName("radioButton_zongheng")
        self.horizontalLayout_8.addWidget(self.radioButton_zongheng)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_re = QtWidgets.QLabel(self.centralwidget)
        self.label_re.setTextFormat(QtCore.Qt.AutoText)
        self.label_re.setObjectName("label_re")
        self.horizontalLayout_2.addWidget(self.label_re)
        self.comboBox_re = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_re.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_re.setEditable(True)
        self.comboBox_re.setObjectName("comboBox_re")
        self.comboBox_re.addItem("")
        self.comboBox_re.addItem("")
        self.comboBox_re.addItem("")
        self.comboBox_re.addItem("")
        self.comboBox_re.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_re)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textEdit_chapter = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.textEdit_chapter.setFont(font)
        self.textEdit_chapter.setObjectName("textEdit_chapter")
        self.verticalLayout.addWidget(self.textEdit_chapter)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_cover = QtWidgets.QLabel(self.centralwidget)
        self.label_cover.setMaximumSize(QtCore.QSize(210, 280))
        self.label_cover.setScaledContents(True)
        self.label_cover.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cover.setObjectName("label_cover")
        self.verticalLayout_2.addWidget(self.label_cover)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_6.addWidget(self.label_title)
        self.lineEdit_title = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_title.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.horizontalLayout_6.addWidget(self.lineEdit_title)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_author = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_author.setFont(font)
        self.label_author.setObjectName("label_author")
        self.horizontalLayout_5.addWidget(self.label_author)
        self.lineEdit_author = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_author.setObjectName("lineEdit_author")
        self.horizontalLayout_5.addWidget(self.lineEdit_author)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_get_info = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_get_info.setObjectName("pushButton_get_info")
        self.horizontalLayout_4.addWidget(self.pushButton_get_info)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.setStretch(0, 4)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label_bookpage.setBuddy(self.lineEdit_bookpage)
        self.label_re.setBuddy(self.comboBox_re)
        self.label_title.setBuddy(self.lineEdit_title)
        self.label_author.setBuddy(self.lineEdit_author)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EpubBuilder"))
        self.pushButton_edit_text.setText(_translate("MainWindow", "编辑文本"))
        self.pushButton_start_build.setText(_translate("MainWindow", "开始"))
        self.label_bookpage.setText(_translate("MainWindow", "书页网址"))
        self.radioButton_qidian.setText(_translate("MainWindow", "起点"))
        self.radioButton_chuangshi.setText(_translate("MainWindow", "创世"))
        self.radioButton_zongheng.setText(_translate("MainWindow", "纵横"))
        self.label_re.setText(_translate("MainWindow", "章节划分正则表达式"))
        self.comboBox_re.setItemText(0, _translate("MainWindow", "^(序|第[\\d零〇一二两三四五六七八九十百千]{0,10})章.{0,20}$"))
        self.comboBox_re.setItemText(1, _translate("MainWindow", "^第[\\d零〇一二两三四五六七八九十百千]{0,10}卷.{0,20}(序|第[\\d零〇一二三四五六七八九十百千]{0,10})章.{0,20}$"))
        self.comboBox_re.setItemText(2, _translate("MainWindow", "^.{0,5}第[\\d零〇一二两三四五六七八九十百千]{0,10}章.{0,20}$"))
        self.comboBox_re.setItemText(3, _translate("MainWindow", "^\\d{1,4}.{1,30}$"))
        self.comboBox_re.setItemText(4, _translate("MainWindow", "^[\\d零〇一二两三四五六七八九十百千]{1,10}[、 ]{1,3}.{0,20}$"))
        self.label_cover.setText(_translate("MainWindow", "封面"))
        self.label_title.setText(_translate("MainWindow", "书名："))
        self.label_author.setText(_translate("MainWindow", "作者："))
        self.pushButton_get_info.setText(_translate("MainWindow", "抓取信息"))

